//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotecaContextContainer : DbContext
    {
        public BibliotecaContextContainer()
            : base("name=BibliotecaContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Autor> AutorSet { get; set; }
        public virtual DbSet<Clasificacion> ClasificacionSet { get; set; }
        public virtual DbSet<Genero> GeneroSet { get; set; }
        public virtual DbSet<Editorial> EditorialSet { get; set; }
        public virtual DbSet<Libro> LibroSet { get; set; }
        public virtual DbSet<Prestamo> PrestamoSet { get; set; }
        public virtual DbSet<Configuracion> ConfiguracionSet { get; set; }
    }
}
