//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int LibroId { get; set; }
        public string Titulo { get; set; }
        public string Descripción { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> StockDisponible { get; set; }
        public byte[] Imagen { get; set; }
        public int AutorAutorId { get; set; }
        public int ClasificacionClasificacionId { get; set; }
        public int GeneroGeneroId { get; set; }
        public int EditorialEditorialId { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Clasificacion Clasificacion { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Editorial Editorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}
