//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int PrestamoId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public string UsuarioDNI { get; set; }
        public int LibroLibroId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
